# version: '3'

# services:

#   # Proxies requests to internal services
#   reverse-proxy:
#     image: nginx:latest
#     container_name: reverse-proxy-demo
#     depends_on:
#         - microservice1
#         - microservice2
#     ports:
#       - 80:80
#       - 443:443

#   microservice1:
#     image: microservice1
#     container_name: microservice1
#     build:
#       context: ./microservice1
#     ports:
#       - 9090:5000
#     restart: on-failure

#   microservice2:
#     image: microservice2
#     container_name: microservice2
#     build:
#       context: ./microservice2
#     ports:
#       - 9091:5002
#     restart: on-failure